# Generated by Django 3.0.6 on 2020-05-18 08:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?91?\\d{6,9}$')])),
                ('location', models.CharField(max_length=40)),
                ('designation', models.CharField(choices=[('WI', 'Work Inspector'), ('JE', 'Junior Engineer'), ('DEE', 'Deputy Executive Engineer')], max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('major', models.CharField(max_length=30)),
                ('front', models.DecimalField(decimal_places=10, max_digits=15)),
                ('rear_sill', models.DecimalField(decimal_places=10, max_digits=15)),
                ('vent', models.DecimalField(decimal_places=10, max_digits=15)),
                ('opening', models.DecimalField(decimal_places=10, max_digits=15)),
                ('driving_head', models.DecimalField(decimal_places=10, max_digits=15)),
                ('discharge', models.DecimalField(decimal_places=10, max_digits=15)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
