# Generated by Django 3.0.6 on 2020-05-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200519_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='front',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='opening',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='rear_sill',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='vent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
